const BinarySearchTreeObj = require('../base/BinarySearchTree')
const BinarySearchTree = BinarySearchTreeObj.BinarySearchTree
let tree = new BinarySearchTree()
tree.insert(10)
tree.insert(11)
tree.insert(7)
tree.insert(5)
tree.insert(9)
tree.insert(18)
tree.insert(6)
tree.insert(6)
tree.insert(6)
tree.insert(6)
tree.insert(6)
let str = ''
let conso = (value) => str += value + ' '
tree.preOrderTraverse(conso)
let result = tree.search(10)
console.log(result)
tree.remove(10)
result = tree.search(10)
console.log(result)
tree.insert(10)
result = tree.search(10)
console.log(result)
