const obj = require('../base/LinkedList')
const LinkedList = obj.LinkedList
let list = new LinkedList()
list.push(0)
list.push(1)
list.push(2)
list.push(3)
list.push(4)
list.push(5)
list.push(6)
list.push(7)
list.push(8)
list.push(9)
list.removeAt(2)
list.removeAt(3)
console.log(list.removeAt(0))
